spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/kiranaconnect}
      database: ${MONGODB_DATABASE:kiranaconnect}
  
kiranaconnect:
  app:
    jwtSecret: ${JWT_SECRET:KiranaConnectSecureSecretKey2026NewVersion}
    jwtExpirationMs: 86400000 # 24 hours
    allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,https://kirana-connect-gray.vercel.app}
  razorpay:
    keyId: ${RAZORPAY_KEY_ID:}
    keySecret: ${RAZORPAY_KEY_SECRET:}
  google:
    search:
      apiKey: ${GOOGLE_SEARCH_API_KEY:}
      cxId: ${GOOGLE_SEARCH_CX_ID:}
  serpapi:
    key: ${SERPAPI_KEY:}

server:
  port: ${PORT:8080}
